CREATE TABLE IF NOT EXISTS `glpi_plugin_maintenancecosts_materials` (
   `id` int unsigned NOT NULL AUTO_INCREMENT,
   `entities_id` int unsigned NOT NULL DEFAULT '0',
   `is_recursive` tinyint NOT NULL DEFAULT '0',
   `code` varchar(64) NOT NULL DEFAULT '',
   `name` varchar(255) NOT NULL DEFAULT '',
   `description` text NULL,
   `unit` varchar(32) NOT NULL DEFAULT '',
   `category` varchar(255) NOT NULL DEFAULT '',
   `is_active` tinyint NOT NULL DEFAULT '1',
   `date_creation` timestamp NULL DEFAULT NULL,
   `date_mod` timestamp NULL DEFAULT NULL,
   PRIMARY KEY (`id`),
   UNIQUE KEY `unicity_code` (`code`),
   KEY `idx_entity` (`entities_id`),
   KEY `idx_recursive` (`is_recursive`),
   KEY `idx_active` (`is_active`),
   KEY `idx_name` (`name`),
   KEY `idx_category` (`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `glpi_plugin_maintenancecosts_prices` (
   `id` int unsigned NOT NULL AUTO_INCREMENT,
   `plugin_maintenancecosts_materials_id` int unsigned NOT NULL DEFAULT '0',
   `competence` varchar(7) NOT NULL DEFAULT '',
   `unit_price` decimal(20,6) NOT NULL DEFAULT '0.000000',
   `quote_quantity` decimal(20,6) NOT NULL DEFAULT '0.000000',
   `quote_price_1` decimal(20,6) NOT NULL DEFAULT '0.000000',
   `quote_price_2` decimal(20,6) NOT NULL DEFAULT '0.000000',
   `quote_price_3` decimal(20,6) NOT NULL DEFAULT '0.000000',
   `price_type` varchar(32) NOT NULL DEFAULT 'sinapi',
   `source` varchar(255) NOT NULL DEFAULT '',
   `plugin_maintenancecosts_importbatches_id` int unsigned NOT NULL DEFAULT '0',
   `users_id` int unsigned NOT NULL DEFAULT '0',
   `comment` text NULL,
   `date_creation` timestamp NULL DEFAULT NULL,
   `date_mod` timestamp NULL DEFAULT NULL,
   PRIMARY KEY (`id`),
   KEY `idx_material` (`plugin_maintenancecosts_materials_id`),
   KEY `idx_competence` (`competence`),
   KEY `idx_price_type` (`price_type`),
   KEY `idx_importbatch` (`plugin_maintenancecosts_importbatches_id`),
   KEY `idx_user` (`users_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `glpi_plugin_maintenancecosts_pricehistories` (
   `id` int unsigned NOT NULL AUTO_INCREMENT,
   `plugin_maintenancecosts_materials_id` int unsigned NOT NULL DEFAULT '0',
   `plugin_maintenancecosts_prices_id` int unsigned NOT NULL DEFAULT '0',
   `plugin_maintenancecosts_importbatches_id` int unsigned NOT NULL DEFAULT '0',
   `competence` varchar(7) NOT NULL DEFAULT '',
   `price_type` varchar(32) NOT NULL DEFAULT 'sinapi',
   `old_unit_price` decimal(20,6) NOT NULL DEFAULT '0.000000',
   `new_unit_price` decimal(20,6) NOT NULL DEFAULT '0.000000',
   `source` varchar(255) NOT NULL DEFAULT '',
   `users_id` int unsigned NOT NULL DEFAULT '0',
   `justification` text NULL,
   `date_creation` timestamp NULL DEFAULT NULL,
   PRIMARY KEY (`id`),
   KEY `idx_material` (`plugin_maintenancecosts_materials_id`),
   KEY `idx_price` (`plugin_maintenancecosts_prices_id`),
   KEY `idx_importbatch` (`plugin_maintenancecosts_importbatches_id`),
   KEY `idx_competence` (`competence`),
   KEY `idx_price_type` (`price_type`),
   KEY `idx_user` (`users_id`),
   KEY `idx_date_creation` (`date_creation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `glpi_plugin_maintenancecosts_materialorigins` (
   `id` int unsigned NOT NULL AUTO_INCREMENT,
   `name` varchar(255) NOT NULL DEFAULT '',
   `is_active` tinyint NOT NULL DEFAULT '1',
   `comment` text NULL,
   `date_creation` timestamp NULL DEFAULT NULL,
   `date_mod` timestamp NULL DEFAULT NULL,
   PRIMARY KEY (`id`),
   KEY `idx_active` (`is_active`),
   KEY `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `glpi_plugin_maintenancecosts_costcenters` (
   `id` int unsigned NOT NULL AUTO_INCREMENT,
   `entities_id` int unsigned NOT NULL DEFAULT '0',
   `is_recursive` tinyint NOT NULL DEFAULT '0',
   `code` varchar(64) NOT NULL DEFAULT '',
   `name` varchar(255) NOT NULL DEFAULT '',
   `address` text NULL,
   `floor` varchar(64) NOT NULL DEFAULT '',
   `campus` varchar(255) NOT NULL DEFAULT '',
   `academic_unit` varchar(255) NOT NULL DEFAULT '',
   `department` varchar(255) NOT NULL DEFAULT '',
   `division` varchar(255) NOT NULL DEFAULT '',
   `section` varchar(255) NOT NULL DEFAULT '',
   `siorg_code` varchar(64) NOT NULL DEFAULT '',
   `siorg_acronym` varchar(64) NOT NULL DEFAULT '',
   `responsible` varchar(255) NOT NULL DEFAULT '',
   `usage_type` varchar(255) NOT NULL DEFAULT '',
   `description` text NULL,
   `locations_id` int unsigned NOT NULL DEFAULT '0',
   `users_id` int unsigned NOT NULL DEFAULT '0',
   `is_active` tinyint NOT NULL DEFAULT '1',
   `comment` text NULL,
   `date_creation` timestamp NULL DEFAULT NULL,
   `date_mod` timestamp NULL DEFAULT NULL,
   PRIMARY KEY (`id`),
   UNIQUE KEY `unicity_code` (`code`),
   KEY `idx_entity` (`entities_id`),
   KEY `idx_recursive` (`is_recursive`),
   KEY `idx_location` (`locations_id`),
   KEY `idx_user` (`users_id`),
   KEY `idx_active` (`is_active`),
   KEY `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `glpi_plugin_maintenancecosts_costcenters_legacy` (
   `id` int unsigned NOT NULL AUTO_INCREMENT,
   `entities_id` int unsigned NOT NULL DEFAULT '0',
   `is_recursive` tinyint NOT NULL DEFAULT '0',
   `code` varchar(64) NOT NULL DEFAULT '',
   `name` varchar(255) NOT NULL DEFAULT '',
   `address` text NULL,
   `floor` varchar(64) NOT NULL DEFAULT '',
   `campus` varchar(255) NOT NULL DEFAULT '',
   `academic_unit` varchar(255) NOT NULL DEFAULT '',
   `department` varchar(255) NOT NULL DEFAULT '',
   `division` varchar(255) NOT NULL DEFAULT '',
   `section` varchar(255) NOT NULL DEFAULT '',
   `siorg_code` varchar(64) NOT NULL DEFAULT '',
   `siorg_acronym` varchar(64) NOT NULL DEFAULT '',
   `responsible` varchar(255) NOT NULL DEFAULT '',
   `usage_type` varchar(255) NOT NULL DEFAULT '',
   `description` text NULL,
   `locations_id` int unsigned NOT NULL DEFAULT '0',
   `users_id` int unsigned NOT NULL DEFAULT '0',
   `is_active` tinyint NOT NULL DEFAULT '1',
   `comment` text NULL,
   `date_creation` timestamp NULL DEFAULT NULL,
   `date_mod` timestamp NULL DEFAULT NULL,
   PRIMARY KEY (`id`),
   UNIQUE KEY `unicity_code` (`code`),
   KEY `idx_entity` (`entities_id`),
   KEY `idx_recursive` (`is_recursive`),
   KEY `idx_location` (`locations_id`),
   KEY `idx_user` (`users_id`),
   KEY `idx_active` (`is_active`),
   KEY `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `glpi_plugin_maintenancecosts_ticketmaterials` (
   `id` int unsigned NOT NULL AUTO_INCREMENT,
   `entities_id` int unsigned NOT NULL DEFAULT '0',
   `itemtype` varchar(100) NOT NULL DEFAULT 'Ticket',
   `items_id` int unsigned NOT NULL DEFAULT '0',
   `tickets_id` int unsigned NOT NULL DEFAULT '0',
   `plugin_maintenancecosts_materials_id` int unsigned NOT NULL DEFAULT '0',
   `plugin_maintenancecosts_costcenters_id` int unsigned NOT NULL DEFAULT '0',
   `costcenter_source` varchar(16) NOT NULL DEFAULT 'new',
   `plugin_maintenancecosts_materialorigins_id` int unsigned NOT NULL DEFAULT '0',
   `contracts_id` int unsigned NOT NULL DEFAULT '0',
   `contractcosts_id` int unsigned NOT NULL DEFAULT '0',
   `ticketcosts_id` int unsigned NOT NULL DEFAULT '0',
   `price_type` varchar(32) NOT NULL DEFAULT 'sinapi',
   `quantity` decimal(20,6) NOT NULL DEFAULT '0.000000',
   `unit` varchar(32) NOT NULL DEFAULT '',
   `unit_price_applied` decimal(20,6) NOT NULL DEFAULT '0.000000',
   `total_price` decimal(20,6) NOT NULL DEFAULT '0.000000',
   `competence` varchar(7) NOT NULL DEFAULT '',
   `consumption_date` date DEFAULT NULL,
   `users_id` int unsigned NOT NULL DEFAULT '0',
   `comment` text NULL,
   `is_deleted` tinyint NOT NULL DEFAULT '0',
   `deleted_at` timestamp NULL DEFAULT NULL,
   `deleted_by` int unsigned NOT NULL DEFAULT '0',
   `delete_reason` text NULL,
   `date_creation` timestamp NULL DEFAULT NULL,
   `date_mod` timestamp NULL DEFAULT NULL,
   PRIMARY KEY (`id`),
   KEY `idx_entity` (`entities_id`),
   KEY `idx_item` (`itemtype`, `items_id`),
   KEY `idx_ticket` (`tickets_id`),
   KEY `idx_material` (`plugin_maintenancecosts_materials_id`),
   KEY `idx_costcenter` (`plugin_maintenancecosts_costcenters_id`),
   KEY `idx_costcenter_source` (`costcenter_source`),
   KEY `idx_materialorigin` (`plugin_maintenancecosts_materialorigins_id`),
   KEY `idx_contract` (`contracts_id`),
   KEY `idx_contractcost` (`contractcosts_id`),
   KEY `idx_ticketcost` (`ticketcosts_id`),
   KEY `idx_price_type` (`price_type`),
   KEY `idx_user` (`users_id`),
   KEY `idx_competence` (`competence`),
   KEY `idx_consumption_date` (`consumption_date`),
   KEY `idx_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `glpi_plugin_maintenancecosts_ticketcostcenters` (
   `id` int unsigned NOT NULL AUTO_INCREMENT,
   `tickets_id` int unsigned NOT NULL DEFAULT '0',
   `entities_id` int unsigned NOT NULL DEFAULT '0',
   `plugin_maintenancecosts_costcenters_id` int unsigned NOT NULL DEFAULT '0',
   `costcenter_source` varchar(16) NOT NULL DEFAULT 'legacy',
   `users_id` int unsigned NOT NULL DEFAULT '0',
   `date_creation` timestamp NULL DEFAULT NULL,
   `date_mod` timestamp NULL DEFAULT NULL,
   PRIMARY KEY (`id`),
   UNIQUE KEY `uniq_ticket` (`tickets_id`),
   KEY `idx_entity` (`entities_id`),
   KEY `idx_costcenter` (`plugin_maintenancecosts_costcenters_id`),
   KEY `idx_source` (`costcenter_source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `glpi_plugin_maintenancecosts_importbatches` (
   `id` int unsigned NOT NULL AUTO_INCREMENT,
   `filename` varchar(255) NOT NULL DEFAULT '',
   `competence` varchar(7) NOT NULL DEFAULT '',
   `price_type` varchar(32) NOT NULL DEFAULT 'sinapi',
   `total_rows` int unsigned NOT NULL DEFAULT '0',
   `imported_rows` int unsigned NOT NULL DEFAULT '0',
   `error_rows` int unsigned NOT NULL DEFAULT '0',
   `users_id` int unsigned NOT NULL DEFAULT '0',
   `status` varchar(32) NOT NULL DEFAULT '',
   `log` longtext NULL,
   `date_creation` timestamp NULL DEFAULT NULL,
   `date_mod` timestamp NULL DEFAULT NULL,
   PRIMARY KEY (`id`),
   KEY `idx_competence` (`competence`),
   KEY `idx_price_type` (`price_type`),
   KEY `idx_user` (`users_id`),
   KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `glpi_plugin_maintenancecosts_configs` (
   `id` int unsigned NOT NULL AUTO_INCREMENT,
   `is_enabled` tinyint NOT NULL DEFAULT '1',
   `costcenter_required` tinyint NOT NULL DEFAULT '0',
   `allow_manual_unit_price` tinyint NOT NULL DEFAULT '0',
   `default_competence_mode` varchar(32) NOT NULL DEFAULT 'latest',
   `allowed_itilcategories` text NULL,
   `date_creation` timestamp NULL DEFAULT NULL,
   `date_mod` timestamp NULL DEFAULT NULL,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `glpi_plugin_maintenancecosts_configentities` (
   `id` int unsigned NOT NULL AUTO_INCREMENT,
   `entities_id` int unsigned NOT NULL DEFAULT '0',
   `is_recursive` tinyint NOT NULL DEFAULT '0',
   `is_active` tinyint NOT NULL DEFAULT '1',
   `users_id` int unsigned NOT NULL DEFAULT '0',
   `date_creation` timestamp NULL DEFAULT NULL,
   `date_mod` timestamp NULL DEFAULT NULL,
   PRIMARY KEY (`id`),
   UNIQUE KEY `unicity_entity_scope` (`entities_id`, `is_recursive`),
   KEY `idx_entity` (`entities_id`),
   KEY `idx_recursive` (`is_recursive`),
   KEY `idx_active` (`is_active`),
   KEY `idx_user` (`users_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `glpi_plugin_maintenancecosts_auditlogs` (
   `id` int unsigned NOT NULL AUTO_INCREMENT,
   `itemtype` varchar(100) NOT NULL DEFAULT '',
   `items_id` int unsigned NOT NULL DEFAULT '0',
   `entities_id` int unsigned NOT NULL DEFAULT '0',
   `action` varchar(64) NOT NULL DEFAULT '',
   `users_id` int unsigned NOT NULL DEFAULT '0',
   `old_value` longtext NULL,
   `new_value` longtext NULL,
   `comment` text NULL,
   `date_creation` timestamp NULL DEFAULT NULL,
   PRIMARY KEY (`id`),
   KEY `idx_item` (`itemtype`, `items_id`),
   KEY `idx_entity` (`entities_id`),
   KEY `idx_action` (`action`),
   KEY `idx_user` (`users_id`),
   KEY `idx_date_creation` (`date_creation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
